suleyman: hexgame.cpp hexgame.h main.cpp
	g++ -std=c++11 main.cpp hexgame.cpp -o 1801042656
	./1801042656

debug:
	g++ -std=c++11 -g main.cpp hexgame.cpp -o 1801042656
	gdb -q ./1801042656

error:
	g++ -std=c++11 main.cpp hexgame.cpp -Wall -Wextra -o 1801042656
	./1801042656

valgrind:
	g++ -std=c++11 main.cpp hexgame.cpp -o 1801042656
	valgrind ./1801042656