suleyman: hexgame.cpp hexgame.h main.cpp
	c++ -std=c++11 main.cpp hexgame.cpp -o 1801042656
	./1801042656

debug:
	c++ -std=c++11 -g main.cpp hexgame.cpp -o 1801042656debugfile
	gdb ./1801042656debugfile

error:
	c++ -std=c++11 main.cpp hexgame.cpp -Wall -Wextra -o 1801042656
	./1801042656
