suleyman: AbstractHex.cpp AbstractHex.h HexVector.h HexArray1D.h HexAdapter.h main.cpp
	g++ -std=c++11 main.cpp AbstractHex.cpp HexVector.cpp HexArray1D.cpp HexAdapter.cpp -o 1801042656
	./1801042656

debug:
	g++ -std=c++11 -g main.cpp AbstractHex.cpp HexVector.cpp HexArray1D.cpp HexAdapter.cpp -o 1801042656
	gdb -q ./1801042656

error:
	g++ -std=c++11 main.cpp AbstractHex.cpp HexVector.cpp HexArray1D.cpp HexAdapter.cpp -Wall -Wextra -o 1801042656
	./1801042656

valgrind:
	g++ -std=c++11 main.cpp AbstractHex.cpp HexVector.cpp HexArray1D.cpp HexAdapter.cpp -o 1801042656
	valgrind ./1801042656

make2:
	g++ -std=c++11 main2.cpp AbstractHex.cpp HexVector.cpp HexArray1D.cpp HexAdapter.cpp -o 1801042656
	./1801042656

debug2:
	g++ -std=c++11 -g main2.cpp AbstractHex.cpp HexVector.cpp HexArray1D.cpp HexAdapter.cpp -o 1801042656
	gdb -q ./1801042656

error2:
	g++ -std=c++11 main2.cpp AbstractHex.cpp HexVector.cpp HexArray1D.cpp HexAdapter.cpp -Wall -Wextra -o 1801042656
	./1801042656